# This is a basic workflow to help you get started with Actions

name: Test-Build

# Controls when the workflow will run
on: [workflow_dispatch, push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Node
      uses: action/setup-node@latest
      with:
        node-version: '12x'
    
    - name: Install newman
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra
    - name: Make directory for results
      run: mkdir -p testResults

    - name: Run POSTMAN collection
      run: |
        newman run ./serverest-tests/ServeRest-Testes.postman_collection.json -r htmlextra --reporter-htmlextra-export ./testResults/htmlreport.html
    - name: Output the run Details
      uses: actions/upload-artifact@v4
      with:
        name: RunReports
        path: testResults
