# This is a basic workflow to help you get started with Actions

name: Test-Build

# Controls when the workflow will run
on: [workflow_dispatch, push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-api:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: '24.3.0'
    
    - name: Install newman
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra
        npm install -g newman-reporter-json

    - name: Run POSTMAN collection
      run: |
        newman run ./ServeRest-Testes.postman_collection.json -r cli,json --reporter-json-export
    
    
